# Generated by Django 4.2.29 on 2026-03-26 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='房型名称')),
                ('description', models.TextField(blank=True, verbose_name='房型描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('capacity', models.PositiveIntegerField(default=2, verbose_name='容纳人数')),
                ('size', models.PositiveIntegerField(default=30, verbose_name='房间面积(平方米)')),
                ('amenities', models.JSONField(default=list, help_text='如WiFi、空调、电视等', verbose_name='设施')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_types/', verbose_name='房型图片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '房型',
                'verbose_name_plural': '房型',
                'db_table': 'room_types',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, unique=True, verbose_name='房间号')),
                ('floor', models.PositiveIntegerField(verbose_name='楼层')),
                ('status', models.CharField(choices=[('available', '空闲'), ('occupied', '已入住'), ('maintenance', '维护中'), ('cleaning', '清洁中')], default='available', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='房间描述')),
                ('images', models.JSONField(default=list, verbose_name='房间图片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.roomtype', verbose_name='房型')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
                'db_table': 'rooms',
                'ordering': ['room_number'],
            },
        ),
    ]
