# Generated by Django 4.2.29 on 2026-03-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='房型图片'),
        ),
    ]
