# Generated by Django 4.2.29 on 2026-03-28 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_roomtype_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='images',
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_types/', verbose_name='房型图片'),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/', verbose_name='房间图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room', verbose_name='房间')),
            ],
            options={
                'verbose_name': '房间图片',
                'verbose_name_plural': '房间图片',
                'db_table': 'room_images',
            },
        ),
    ]
