# Generated by Django 4.2.29 on 2026-03-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_room_images_alter_roomtype_image_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.JSONField(default=list, verbose_name='房间图片'),
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
