# Generated by Django 4.2.29 on 2026-03-26 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='入住日期')),
                ('check_out_date', models.DateField(verbose_name='退房日期')),
                ('guests', models.PositiveIntegerField(default=1, verbose_name='入住人数')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('checked_in', '已入住'), ('checked_out', '已退房'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('special_requests', models.TextField(blank=True, verbose_name='特殊要求')),
                ('contact_name', models.CharField(max_length=50, verbose_name='联系人姓名')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rooms.room', verbose_name='房间')),
            ],
            options={
                'verbose_name': '预订',
                'verbose_name_plural': '预订',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_check_in', models.DateTimeField(auto_now_add=True, verbose_name='实际入住时间')),
                ('actual_check_out', models.DateTimeField(blank=True, null=True, verbose_name='实际退房时间')),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='id_cards/', verbose_name='身份证照片')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='押金')),
                ('deposit_returned', models.BooleanField(default=False, verbose_name='押金已退')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_record', to='bookings.booking', verbose_name='预订')),
            ],
            options={
                'verbose_name': '入住记录',
                'verbose_name_plural': '入住记录',
                'db_table': 'checkin_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
