# Generated by Django 4.2.29 on 2026-03-27 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('notification_type', models.CharField(choices=[('system', '系统通知'), ('booking', '预订通知'), ('payment', '支付通知'), ('promotion', '促销通知'), ('other', '其他')], default='system', max_length=20, verbose_name='类型')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '消息通知',
                'verbose_name_plural': '消息通知',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
