# Generated by Django 4.2.29 on 2026-03-27 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='副标题')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='图片')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='链接')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'banners',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='优惠券码')),
                ('name', models.CharField(max_length=100, verbose_name='优惠券名称')),
                ('coupon_type', models.CharField(choices=[('fixed', '固定金额'), ('percentage', '百分比折扣')], default='fixed', max_length=20, verbose_name='类型')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='固定金额或百分比', max_digits=10, verbose_name='优惠值')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最低消费')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='百分比折扣时有效', max_digits=10, null=True, verbose_name='最大优惠金额')),
                ('total_count', models.PositiveIntegerField(default=100, verbose_name='发放总数')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='已使用数量')),
                ('per_user_limit', models.PositiveIntegerField(default=1, verbose_name='每人限领')),
                ('start_time', models.DateTimeField(verbose_name='生效时间')),
                ('end_time', models.DateTimeField(verbose_name='过期时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
                'db_table': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unused', '未使用'), ('used', '已使用'), ('expired', '已过期')], default='unused', max_length=20, verbose_name='状态')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='领取时间')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='operations.coupon', verbose_name='优惠券')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户优惠券',
                'verbose_name_plural': '用户优惠券',
                'db_table': 'user_coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活动标题')),
                ('description', models.TextField(blank=True, verbose_name='活动描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/', verbose_name='活动图片')),
                ('discount_type', models.CharField(choices=[('percentage', '百分比折扣'), ('fixed', '固定金额'), ('special', '特价')], default='percentage', max_length=20, verbose_name='优惠类型')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='百分比折扣填0-100，固定金额填具体金额', max_digits=10, verbose_name='优惠值')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('paused', '已暂停'), ('ended', '已结束')], default='draft', max_length=20, verbose_name='状态')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('room_types', models.ManyToManyField(blank=True, to='rooms.roomtype', verbose_name='适用房型')),
            ],
            options={
                'verbose_name': '促销活动',
                'verbose_name_plural': '促销活动',
                'db_table': 'promotions',
                'ordering': ['-sort_order', '-created_at'],
            },
        ),
    ]
