# Generated by Django 4.2.29 on 2026-03-27 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(default='#409EFF', max_length=20, verbose_name='标签颜色')),
                ('description', models.TextField(blank=True, verbose_name='标签描述')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tags',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomTypeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_tags', to='rooms.roomtype', verbose_name='房型')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type_tags', to='tags.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '房型标签',
                'verbose_name_plural': '房型标签',
                'db_table': 'room_type_tags',
                'unique_together': {('room_type', 'tag')},
            },
        ),
    ]
