# Generated by Django 6.0.3 on 2026-03-29 11:58

import apps.payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_no',
            field=models.CharField(default=apps.payments.models.generate_payment_no, editable=False, max_length=64, unique=True, verbose_name='支付单号'),
        ),
    ]
